<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icofdsfix3.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icofdsfix3.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icofdsfix3.ico" />
  </ItemGroup>

</Project>
